version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # For Docker-in-Docker
    environment:
      - JENKINS_OPTS="--httpPort=8080"
  
  # Define your Selenium standalone service if needed
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - jenkins

volumes:
  jenkins_data:
